// <auto-generated />
namespace Haus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_food_components : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_food_components));
        
        string IMigrationMetadata.Id
        {
            get { return "201610290737119_Add_food_components"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
